---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - healthchecker.cattle.io
  resources:
  - httpstatuspollers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - healthchecker.cattle.io
  resources:
  - httpstatuspollers/finalizers
  verbs:
  - update
- apiGroups:
  - healthchecker.cattle.io
  resources:
  - httpstatuspollers/status
  verbs:
  - get
  - patch
  - update
